application: cooklogs
version: 1
runtime: python
api_version: 1

handlers:
- url: /js/
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: cooklogs.py