application: cooklogs
version: 2
runtime: python
api_version: 1

handlers:
- url: /js/
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: cooklogs.py